### ISSUE TITLE
Segmentation Fault when running the project

### ISSUE THREAD

**Issue by Bruce-Ch** [tamimcse/cp-trie#1]
Recently I've been trying to run the project and reproduce the results in "CP-Trie: Cumulative PopCount based Trie for IPv6 Routing Table Lookup in Software and ASIC". 

I followed the README to build and run the program. It was really easy to build and run it. However, I've got a Segmentation Fault.
```
CPU frequency is 1.698019 GHz
Reading FIB from file fibs/ip6/routes-293 .......
-----------------Generating repeated traffic--------------
-----------------Generating sequential traffic--------------
generating sequential traffic withing 20010004011200000000000000000000/40
---------------------Checking SAIL-U--------------------------
SAIL-U insertion time per prefix = 369.433558 microsec
SAIL-U memory consumption = 35.031738 MB
SAIL-U lookup throughput for real traffic = 1.691254 Mlps
SAIL-U lookup throughput for random traffic = 175.596913 Mlps
SAIL-U lookup throughput for sequential traffic = 55.873109 Mlps
SAIL-U lookup throughput for prefix traffic = 30.857608 Mlps
SAIL-U lookup throughput for repeated traffic = 43.764869 Mlps
Segmentation fault (core dumped)
```

I've tried to use `sudo` mode, and still got the same error (the only difference is no "core dumped" this time). I tried to use gdb to find the causes. It seems that the program died in `cptrie_level_cleanup(cptrie_level*) ()`, where some freeing work is conducted. 

I'm running the program on Ubuntu 20.04.3 LTS, and using g++ 9.4.0 to compile the program.

Hope to get some hint here.

**Comment by tamimcse** [comment]
Thanks for filing the issue. Return statement was missing in `sail_level_cleanup()` and `sail_u_cleanup()`, and the newer compiler was generating bad code for that. After adding a return 0, it proceeds further to SAIL_L(Please see the diff below). But, such return statement is missing in few other functions for SAIL_L, Poptrie and CP-Trie. I will fix them and update the github repo soon.

diff --git a/level_sail.c b/level_sail.c
index 473c404..acd2280 100644
--- a/level_sail.c
+++ b/level_sail.c
@@ -43,6 +43,7 @@ int sail_level_cleanup (struct sail_level *c) {
   c->count = 0;
   c->parent = NULL;
   c->chield = NULL;
+  return 0;
 }
 
 int sail_level_print (struct sail_level *c) {
diff --git a/sail_u_ip6.c b/sail_u_ip6.c
index 1d2bd59..73f36bd 100644
--- a/sail_u_ip6.c
+++ b/sail_u_ip6.c
@@ -89,6 +89,7 @@ int sail_u_cleanup() {
   sail_level_cleanup (&sail_u.level120);
   sail_level_cleanup (&sail_u.level128);
   memset(&sail_u, 0, sizeof(sail_u));
+  return 0;
 }

**Comment by Bruce-Ch** [comment]
Great！Now I can run it successfully.
Thank you for your help.
